services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elearning-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    # volumes:
    #   - .:/app  # Remove for production
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - elearning_net
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  elearning_net:
    external: true
