services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elearning-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - elearning_net
    

networks:
  elearning_net:
    external: true
